### PR TITLE
Added subparsers for language prompts

### LINKED ISSUE #29: Adding Sub-Parsers for Language Prompts
Allow additional sub-parsers to be added to the language prompts for refactoring, documentation, bug finding, and unit testing

**Is your feature request related to a problem? Please describe.**
There is currently no way to perform additional actions beyond language conversions using the existing language prompts. This limits the functionality of the CLI tool and the library for certain use cases.

**Describe the solution you'd like**
Add additional sub-parsers to the existing language prompts for actions such as refactoring, documentation, bug finding, and unit testing. This can be done through command line arguments. This would also require that we add additional prompts for each of those features, but would be worthwhile.

**Describe alternatives you've considered**
One alternative would be to create separate CLI tools for each desired action (e.g. a separate tool for refactoring, another for documentation, etc.). However, this approach would result in having multiple tools that are only loosely connected to each other, making it harder to work with in the long run. Another alternative would be to use flags with the existing language prompts to enable additional functionality, but this could become cumbersome as more functionality is added.

### PR DESCRIPTION
**Pull request by JohnnyIrvin**
Closes #29

### CODE REVIEW

**Comment by JohnnyIrvin** [comment]
Assume file bar.py

```
def foo(x, y):
    return x + y
```

A refactor won't work due to the simplicity and GPT will inform you of this.
```
cat bar.py | python -m shell_craft --prompt python --refactor
```

Returns
```
The given code is already a simplified function that returns the sum of its two parameters. There are no bugs and the code is efficient in terms of its simplicity. Therefore, there is nothing to improve unless there are specific requirements or constraints that need to be met.
```

Documentation works fairly well
```
cat bar.py | python -m shell_craft --prompt python --document
```

Return
```
This function adds two input parameters and returns their sum.

Parameters:
- x: A number that needs to be added with y
- y: A number that needs to be added with x

Returns:
- The sum of x and y (x + y)
```

Future parameters could allow for a style guide to determine documentation placement and style.

Testing is good,but without a style guide it assumes things like framework and style of testings.

```
 cat bar.py | python -m shell_craft --prompt python --test
```

Returned

```
def test_foo():
    # Arrange
    x = 5
    y = 10
    
    # Act
    result = foo(x, y)
    
    # Assert
    assert result == 15, "Error: expected result was 15 but actual result was " + str(result)
    
    # Arrange
    x = -5
    y = 3
    
    # Act
    result = foo(x, y)
    
    # Assert
    assert result == -2, "Error: expected result was -2 but actual result was " + str(result)

    # Arrange
    x = 0
    y = 0
    
    # Act
    result = foo(x, y)
    
    # Assert
    assert result == 0, "Error: expected result was 0 but actual result was " + str(result)
```

**Comment by JohnnyIrvin** [comment]
Styling of the existing doc will influence these prompts.

**Comment by JohnnyIrvin** [comment]
More interesting starting with a file of the following returned better results:

```
def foo(x: int, y: int) -> int:
    """ 
    Adds two numbers together and returns their sum.

    Args:
        x (int): The first number.
        y (int): The second number.

    Returns:
        int: The two numbers added together.
    """
    return x + y 

def bar(x, y): 
    return x * y 

def foobar(x, y): 
    return x ** y
```

When running
```
cat bar.py | python -m shell_craft --prompt python --refactor
```

I get amazing results.

```
def foo(x: int, y: int) -> int:
    """
    Adds two numbers together and returns their sum.

    Args:
    x (int): The first number.
    y (int): The second number.

    Returns:
    int: The two numbers added together.
    """
    return x + y


def bar(x: int, y: int) -> int:
    """
    Multiplies two numbers together and returns the product.

    Args:
    x (int): The first number.
    y (int): The second number.

    Returns:
    int: The two numbers multiplied together.
    """
    return x * y


def foobar(x: int, y: int) -> int:
    """
    Raises the first number to the power of the second number and returns the result.

    Args:
    x (int): The base number.
    y (int): The exponent.

    Returns:
    int: The result of raising the base number to the exponent.
    """
    return x ** y
```


Running the actual document command produces slightly better results.

```
cat bar.py | python -m shell_craft --prompt python --document
```

```
def foo(x: int, y: int) -> int:
     """
     Adds two numbers together and returns their sum.
 
     Args:
         x (int): The first number.
         y (int): The second number.
 
     Returns:
         int: The two numbers added together.
     """
     return x + y
 
 def bar(x: int, y: int) -> int:
     """
     Multiplies two numbers together and returns their product.
 
     Args:
         x (int): The first number.
         y (int): The second number.
 
     Returns:
         int: The two numbers multiplied together.
     """
     return x * y
 
 def foobar(x: int, y: int) -> int:
     """
     Raises a number to a power and returns the result.
 
     Args:
         x (int): The base number.
         y (int): The exponent to raise the base number to.
 
     Returns:
         int: The base number raised to the power of the exponent.
     """
     return x ** y
```

And then of course the testing command produces the dream of every developer.
```
cat bar.py | python -m shell_craft --prompt python --test
```

```
def add_numbers(x: int, y: int) -> int:
    """
    Adds two numbers together and returns their sum.

    Args:
        x (int): The first number.
        y (int): The second number.

    Returns:
        int: The two numbers added together.
    """
    return x + y


def multiply_numbers(x: int, y: int) -> int:
    """
    Multiplies two numbers together and returns their product.

    Args:
        x (int): The first number.
        y (int): The second number.

    Returns:
        int: The two numbers multiplied together.
    """
    return x * y


def power(x: int, y: int) -> int:
    """
    Raises x to the power of y and returns the result.

    Args:
        x (int): The base number.
        y (int): The exponent value.

    Returns:
        int: x raised to the power of y.
    """
    return x ** y


# Tests for add_numbers()
def test_add_numbers():
    # Arrange
    x = 5
    y = 10

    # Act
    result = add_numbers(x, y)

    # Assert
    assert result == 15


# Tests for multiply_numbers()
def test_multiply_numbers():
    # Arrange
    x = 5
    y = 10

    # Act
    result = multiply_numbers(x, y)

    # Assert
    assert result == 50


# Tests for power()
def test_power():
    # Arrange
    x = 5
    y = 3

    # Act
    result = power(x, y)

    # Assert
    assert result == 125
```

**Comment by joelfourhman** [comment]
LGTM, tests succeed

**Review by joelfourhman — APPROVED** [review]
all tests and then some worked for me

**Pull request merged**
