### PR TITLE
Add docker

### LINKED ISSUE #14: Dockerization
Enable Shell Craft execution via Docker container 

**Is your feature request related to a problem? Please describe.**

Executing shell craft from a container allows for better isolation, portability and easier installation. Users can avoid installation errors, compiling dependencies and upgrade complexities.

**Describe the solution you'd like**

I would like Shell Craft to be available as a docker image that can be pulled from an image registry like Docker Hub. Running the image launches the Shell Craft environment with all the required dependencies pre-installed, and users can request prompt results through the container.

**Describe alternatives you've considered**

Users that require isolation can install the dependencies in a virtual environment. However, this is time-consuming and has higher overhead compared to using a Docker container.

### PR DESCRIPTION
**Pull request by JohnnyIrvin**
Closes #14

### CODE REVIEW

**Comment by joelfourhman** [comment]
ENV vars do not pass correctly in Windows

**Comment by JohnnyIrvin** [comment]
Needs rebase now for docs.

**Comment by JohnnyIrvin** [comment]
Rebase successful, investigating environment var passing.

**Review by SheepReaper — APPROVED** [review]

**Comment by JohnnyIrvin** [comment]
@joelfourhman It seems that passing in env vars to docker using -e is expected behavior.

_shrug_ If you find something better, we'll add it in then.

**Comment by joelfourhman** [comment]
ok, sounds fine to me

**Pull request merged**
